# Generated by Django 4.1.6 on 2023-02-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
