# Generated by Django 4.1.6 on 2023-02-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.categorymodel')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'post',
            },
        ),
    ]
