# Generated by Django 4.1.6 on 2023-02-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_rename_title_categorymodel_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='summary',
            new_name='title_1',
        ),
    ]
