# Generated by Django 4.1.6 on 2023-02-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_rename_summary_categorymodel_title_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='title_1',
            new_name='title',
        ),
    ]
