# Generated by Django 4.1.6 on 2023-02-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_rename_title_1_categorymodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='title',
            new_name='summary',
        ),
    ]
