# Generated by Django 4.1.6 on 2023-02-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_rename_title_postmodel_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='slug',
        ),
    ]
