# Generated by Django 4.1.6 on 2023-02-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_remove_postmodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='summary',
            new_name='name',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
